source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "trailer_vote-fixtures", path: "../../trailervote-fixtures"
# Specify your gem's dependencies in trailer_vote-api.gemspec
gemspec

