sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3.0
  - 2.4
  - 2.5
  - 2.6
  - rbx-3
  - ruby-head
matrix:
  include:
    - language: ruby
      cache: bundler
      rvm: 2.3.0
      before_install:
        - gem update --system
        - gem --version
        - cd ruby
      install:
        - bundle install --with development --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

    - language: ruby
      cache: bundler
      rvm: 2.4
      before_install:
        - gem update --system
        - gem --version
        - cd ruby
      install:
        - bundle install --with development --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

    - language: ruby
      cache: bundler
      rvm: 2.5
      before_install:
        - gem update --system
        - gem --version
        - cd ruby
      install:
        - bundle install --with development --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

    - language: ruby
      cache: bundler
      rvm: 2.6
      before_install:
        - gem update --system
        - gem --version
        - cd ruby
      install:
        - bundle install --with development --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

    - language: ruby
      cache: bundler
      rvm: rbx-3
      before_install:
        - gem update --system
        - gem --version
        - cd ruby
      install:
        - bundle install --with development --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

    - language: ruby
      cache: bundler
      rvm: ruby-head
      before_install:
        - gem update --system
        - gem --version
        - cd ruby
      install:
        - bundle install --with development --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

    - language: node_js
      cache: yarn
      node_js: node
      before_install:
        - cd javascript

    - language: node_js
      cache: yarn
      node_js: iojs
      before_install:
        - cd javascript

    - language: node_js
      cache: yarn
      node_js: lts/*
      before_install:
        - cd javascript

  allow_failures:
    - language: ruby
      rvm: ruby-head
    - language: ruby
      rvm: rbx-3
    - language: ruby
      rvm: 2.6
    - language: node_js
      node_js: iojs
